✨ feat : Set up the project and create a header & search box
Tabeyouka/project_TABEYOUKA_react-deployment-repo pull request #14
Opened 2023-06-28 11:37 UTC by JOHYEONJUN39

- MUI 모듈 설치
- 헤더작성
  - Logo
  - GNB
  - 사이드 Drawer
- 검색창 작성

2023-06-28 11:47 UTC, devYuMinKim commented on src/components/layout/header/basicMenu/index.tsx
> +        <MenuItem onClick={handleClose}>한국어</MenuItem>
```suggestion
        <MenuItem onClick={handleClose}>한국어</MenuItem>
        <MenuItem onClick={handleClose}>日本語</MenuItem>
        <MenuItem onClick={handleClose}>English</MenuItem>
```
현재 예정 상으로는 구현하지 않을 기능이라 없애거나 주석 처리해둬도 괜찮을 것 같습니다.

2023-06-28 12:07 UTC, devYuMinKim requested changes
고생하셨습니다. 코멘트 부분 체크 부탁드립니다.

2023-06-29 07:00 UTC, d556f8 reviewed
기능상 괜찮은 것 같습니다.
그러나 MainPage와 같은 페이지를 표현하는 컴포넌트는 `src/pages` 라는 디렉토리를 만들어서 넣는 게 좋은 것 같습니다. 
그리고, `restaurantBtn`, `categoryBtn`, `locationBtn`은 거의 공통적인 부분이 많은 것 같습니다.
나중에 개선해봐도 좋을 것 같아용

2023-06-29 07:01 UTC, d556f8 approved these changes

2023-06-29 10:36 UTC, closed without merging